### ISSUE TITLE
eosop-cpp not working with CDT 1.6.1

### ISSUE THREAD

**Issue by zlnvch** [operanditech/eosup#3]
Warning, this tool is deprecated.  Only use eosio-cpp in the future.
In file included from /mnt/dev/contract/contracts/marketplace.cpp:1:
/mnt/dev/contract/contracts/marketplace.hpp:1:10: fatal error: 'eosio/eosio.hpp' file not found
#include <eosio/eosio.hpp>
        ^~~~~~~~~~~~~~~~~

**Comment by andresberrios** [comment]
Done, version 1.0.0 is out on npm (Readme still needs updating)
